name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore MathCore.sln
    - name: Build
      run: dotnet build MathCore.sln --configuration Release --no-restore 
    - name: Tests
      run: dotnet test MathCore/MathCore.csproj
    - name: Publish Hukutka.MathCore
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: MathCore/MathCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
